FROM ev3dev/debian-stretch-cross:latest

RUN sudo apt-get update
RUN sudo apt-get -y install --no-install-recommends gcc g++
RUN sudo apt-get -y install git

# ** [Optional] Uncomment this section to install additional packages. **
#
# RUN apt-get update \
#     && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

